[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox.toml"]

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 17.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

# [[keyboard.bindings]]
# chars = "\u0000"
# key = "Space"
# mods = "Control"

[scrolling]
history = 15000

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
opacity = 0.8
blur = true
option_as_alt = "OnlyLeft"
decorations = "buttonless"

[window.padding]
x = 8
y = 8

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
# Send CSI u sequence for Ctrl+i to distinguish it from Tab
key = "i"
mods = "Control"
chars = "\u001b[105;5u"

[mouse]
hide_when_typing = true
