function zvm_config() {
    ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK
    ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
    ZVM_OPPEND_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE

    ZVM_VI_HIGHLIGHT_FOREGROUND=#faf4ed
    ZVM_VI_HIGHLIGHT_BACKGROUND=#907aa9
    ZVM_VI_HIGHLIGHT_EXTRASTYLE=bold,underline
}
