{ lib
, buildNpmPackage
, fetchFromGitHub
, nodejs_20
}:

let
  # Manual version - update when you want a new version
  version = "0.5.13";

  # You may need to update these hashes when updating the version
  srcHash = "sha256-CzVzBvuK/RRYxFA4wOhkIXuXjoxWHHRnzUpGuvl9kQU=";
  depsHash = "sha256-6r1dwWpDr4CEYr2GWWKXindP/T2P45jVj1oqyrd7IAg=";

  src = fetchFromGitHub {
    owner = "sst";
    repo = "opencode";
    rev = "v${version}";
    hash = srcHash;
  };

in
buildNpmPackage rec {
  pname = "opencode";
  inherit version src;
  nodejs = nodejs_20;
  npmDepsHash = depsHash;

  # Skip build step as we're just installing the CLI
  dontNpmBuild = true;
  AUTHORIZED = "1";

  # Use the package-lock.json file generated by the update script
  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  postInstall = ''
    node $out/postinstall.mjs
  '';

  meta = {
    description = "Build copilots that understand your entire codebase";
    homepage = "https://opencode.ai";
    downloadPage = "https://www.npmjs.com/package/opencode-ai";
    license = lib.licenses.mit;
    mainProgram = "opencode";
  };
}
