[palettes.gruvbox]
# Blacks - Extra dark backgrounds
black0 = "#1d2021"
black1 = "#282828"
# Slightly darker than bg. Very useful for certain popups
black2 = "#32302f"

# Grays - Background variants
# Soft background
gray0 = "#32302f"
# Standard background
gray1 = "#3c3836"
gray2 = "#504945"
gray3 = "#665c54"
gray4 = "#7c6f64"

# Medium gray
# From gruvbox gray
gray5 = "#928374"

# Dim white
# default fg, warm tint
white0_normal = "#d5c4a1"
# brighter variant
white0_reduce_blue = "#ebdbb2"

# Foreground variants
white1 = "#ebdbb2"
white2 = "#f2e5bc"
white3 = "#fbf1c7"

# Blues - Gruvbox blue variants
blue0 = "#458588"
blue1 = "#83a598"
blue2 = "#83a598"

cyan_base = "#689d6a"
cyan_bright = "#8ec07c"
cyan_dim = "#427b58"

# Aurora
# Red variants
red_base = "#cc241d"
red_bright = "#fb4934"
red_dim = "#9d0006"

orange_base = "#d65d0e"
orange_bright = "#fe8019"
orange_dim = "#af3a03"

yellow_base = "#d79921"
yellow_bright = "#fabd2f"
yellow_dim = "#b57614"

green_base = "#98971a"
green_bright = "#b8bb26"
green_dim = "#79740e"

magenta_base = "#b16286"
magenta_bright = "#d3869b"
magenta_dim = "#8f3f71"
