# alias gl="git log --graph --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%an%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)- %s%C(reset)' --all"
# alias gdh="git diff HEAD"
# alias gs="git status"
# alias gd="git diff";
# alias gcm="git commit -m "
alias cp="cp -i"
alias rm="rm -i"
alias mkdir="mkdir -p"
alias which="type"
alias asr="atuin scripts run"
