ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BEAM
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
ZVM_OPPEND_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE

ZVM_VI_HIGHLIGHT_FOREGROUND=#faf4ed           # Hex value
ZVM_VI_HIGHLIGHT_BACKGROUND=#907aa9           # Hex value
ZVM_VI_HIGHLIGHT_EXTRASTYLE=bold,underline    # bold and underline
