# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'ofirgall/tmux-window-name' 		# smart windows name set
set -g @plugin 'arcticicestudio/nord-tmux'		# tmux themes
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# yank in tmux
#
set -g @plugin 'tmux-plugins/tmux-yank'
# predefine layout for tmux session
run '~/.tmux/plugins/tpm/tpm'
