# 1. Ergonomic Prefix (Changes C-b to C-Space)
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# 2. Match Keyboard Layout (Starts windows number at 1 instead of 0)
set-option -g base-index 1
set-window-option -g pane-base-index 1

# 3. Fix Neovim/Vim Escape Delay
set -sg escape-time 0

# 4. Open new windows and panes in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

source ~/.config/tmux/tpm.conf
